### ISSUE TITLE
Bad Routing on `topology subnet`

### ISSUE THREAD

**Issue by AlmogBaku** [schwabe/ics-openvpn-real#14]
For some reason, we had an issue with the routing *after establishing connection- every request throws an dns error.
After commenting the server's derective of `topology subnet` the problem solved.

**Comment by schwabe** [comment]
This sounds like a server configuration problem instead of client configuration

**Comment by AlmogBaku** [comment]
@schwabe it's not.
The "openvpn connect" client resloves the routing es expected with `topology sebnet`.

**Comment by schwabe** [comment]
can you then send me a log with topology subnet of the client?
